name: Sync images

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  sync-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: hhyasdf/image-sync-action@v1.1
        with:
          auth_file: ./image-sync/auth.yml
          images_file: ./image-sync/images.yml
          version: latest
          proc: 20
        env:
          ACR_USERNAME:  ${{ secrets.ACR_USERNAME }}
          ACR_PASSWORD:  ${{ secrets.ACR_PASSWORD }}